app:
  port: 3000
  pub_dir: "/public"
  cookie_secret: "secret key salt"
  session_secret: "secret key salt"
  auth:
    passthrough:
      email: "sys@admin"
      pass: "cross"
    domain: "gmail.com"
    bytesize: 128
    iterations: 12000
  audit:
    clean: 7
  records:
    expire: 0
    locked: 0
    comment: 1
    upload: 0
email:
  smtp: ""
  username: ""
  password: ""
db:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: ""
  password: ""
  database: ""
  charset: "utf8"
  collate: "utf8_general_ci"
  initialConnections: 1
  maxConnections: 5
  maxIdleTime: 30